# Generated by Django 3.0.3 on 2020-05-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='Comment',
            field=models.CharField(max_length=100, verbose_name='Комментарий'),
        ),
    ]
