# Generated by Django 3.0.3 on 2020-05-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0005_auto_20200530_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='object_name',
            field=models.CharField(max_length=100, verbose_name='Название объекта'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Тип нарушения'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='violator_profession',
            field=models.CharField(max_length=100, verbose_name='Профессия нарушителя'),
        ),
        migrations.DeleteModel(
            name='Object',
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
        migrations.DeleteModel(
            name='ViolationType',
        ),
    ]
