# Generated by Django 3.0.3 on 2020-05-31 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0007_auto_20200530_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'Профессия', 'verbose_name_plural': 'Профессии'},
        ),
        migrations.AlterModelOptions(
            name='violation',
            options={'verbose_name': 'Нарушение', 'verbose_name_plural': 'Нарушения'},
        ),
        migrations.AlterModelOptions(
            name='violationtype',
            options={'verbose_name': 'Тип Нарушения', 'verbose_name_plural': 'Типы Нарушений'},
        ),
    ]
