# Generated by Django 3.0.3 on 2020-05-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=25, verbose_name='Номер')),
                ('owner', models.CharField(max_length=100, verbose_name='Владелец')),
            ],
        ),
    ]
