# Generated by Django 3.0.3 on 2020-05-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='object_name',
            field=models.CharField(default='Без объекта', max_length=100, verbose_name='Название объекта'),
            preserve_default=False,
        ),
    ]
