# Generated by Django 3.0.3 on 2020-05-31 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_employees', '0002_person_object_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
